### ISSUE TITLE
Unmarshal error?

### ISSUE THREAD

**Issue by livefire2015** [veryfi/veryfi-go#7]
I followed the example code and tried several receipts today (including the [Walgreens one on the website](https://www.veryfi.com/receipt-ocr-api/) ), but kept getting this error below about `Document.insurance` field:
```
2022/09/14 14:13:06.738512 ERROR RESTY json: cannot unmarshal number into Go struct field Document.insurance of type string, Attempt 1
2022-09-14T14:13:06.738-0700    ERROR           ProcessDocumentUpload Error: {error 26 0  fail to make a request to Veryfi: json: cannot unmarshal number into Go struct field Document.insurance of type string}
```

* Client: Go NewClientV7
* SDK: veryfi-go v1.0.0

Could you please look into it?

**Comment by hoanhan101** [comment]
Hi, thanks for reporting. I just fixed and released the new version here https://github.com/veryfi/veryfi-go/releases/tag/v1.1.0. Cheer!
